name = "Petal SMP Modpack"
author = "macuguita"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1788b26cfd8586e213be1ce42350789d27b655a33c96310f5d2425bf1ef8513e"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"

[options]
datapack-folder = "resources/datapack/required"
