name = "Petal SMP Modpack"
author = "macuguita"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8389cca5b21104bd646723c45c0908ef7c0dc3b4b3752e80e26d5a8fe20c5d89"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"

[options]
datapack-folder = "resources/datapack/required"
